### ISSUE TITLE
Add static-tables sites to library production proxy-pass rules

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/static-tables#151]
### What maintenance needs to be done?
The static tables sites need to be added to the library production proxy-pass rules

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- In order to display the new sites at the old addresses, and maintain any existing links, we need to add the sites to the proxy-pass rules on production

### Acceptance criteria
- [ ] Update [production proxy-pass rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf) to point https://library.princeton.edu/special-collections/databases/undergraduate-alumni-index-part-1 to https://static-tables-staging.princeton.edu/undergraduate-alumni-index-part-1
- [ ] Update [production proxy-pass rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf) to point https://library.princeton.edu/special-collections/databases/trustee-index-1746-2001 to https://static-tables-staging.princeton.edu/trustee-index-1746-2001 
- [ ] Update [production proxy-pass rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf) to point https://library.princeton.edu/special-collections/databases/undergraduate-alumni-index-part-2 to https://static-tables-staging.princeton.edu/undergraduate-alumni-index-part-2
- [ ] princeton-alumni-weekly-memorial-index
- [ ] Update [production proxy-pass rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf) to point https://library.princeton.edu/special-collections/databases/world-war-ii-memorial-book to https://static-tables-staging.princeton.edu/world-war-ii-memorial-book
- [ ] honorary-degree-index
- [ ] Update [production proxy-pass rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf) to point library.princeton.edu/special-collections/databases/faculty-and-professional-staff-index to https://static-tables-prod.princeton.edu/faculty-and-professional-staff-index

**Comment by kelea99** [comment]
@maxkadel : Mudd stakeholder (Lynn) emailed on 05/29/2024 for review request of all links:

_> ...A while back, Regine Heberlein shared a spreadsheet with you to review. The spreadsheet contained links of Website Databases in need of migration (if it was decided by you and others that they were to be kept).  Those new applications are ready to be previewed by you and tested!  If you could have a look to see if each link is functioning as expected, that would be great. Once signoff for functionality is given, could you please check the box in the column provided to the right of the new links for review? If you have questions or concerns, please do not hesitate contacting me or a member of  Kevin's team (DACS).
> 
> [Spreadsheet for review](https://docs.google.com/spreadsheets/d/1fZLC-j-Eh_9YtxMsPFiPgSJ-ytFIxdpN_UQY0BrUvvM/edit?usp=sharing)_

**Comment by kelea99** [comment]
@kevinreiss when is the migration date for the website? We will need signoff on all of these by what date? Ill share that out with Lynn as soon as I hear from you

**Comment by kelea99** [comment]
Update: Migration Forecast is the first-second week of August 2024.

**Comment by kelea99** [comment]
From Lynn as of 07/26
 I will review these afternoon or first thing on Monday. I will connect with Sara on the new SC site.

**Comment by sandbergja** [comment]
Lynn and SC have approved this.  Rather than adding redirects ourselves, WDS will add redirects when the new website goes live.
