### ISSUE TITLE
Add Economics Working Papers Data Sets

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/static-tables#163]
### User story
I would like to be able to search and browse the .[Economics Working Papers dataset](https://library.princeton.edu/econlib/working-papers). 

### Acceptance criteria

- [x] Create a CSV export in pul_library_drupal for the [data set](https://library.princeton.edu/econlib/working-papers.csv). 
- [x] Page displays the basic Princeton library header
- [x] Page displays the basic Princeton library footer
- [x] Page title is "Economics Working Papers"
- [x] The base path of the application is available at "economics-working-papers". 
- [x] Users can keyword search by Title
- [x] Users can Filter by Publisher
- [x] Ask Bobray if we should add a collection Description (Optional)
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Notes
See the [Current URL](https://library.princeton.edu/econlib/working-papers) to review the existing search options available. 
[Current Data File on Drive](https://drive.google.com/file/d/1JSQ6LSc2Z19SsToEggngTHDg1NkbxAVp/view?usp=drive_link) - File -> Share -> Publish to web -> dropdown change to CSV - >Publish. Copy the url and use it in the config file for the app.

### Collection Description 
Currently no collection description. Need to check with Bobray on this. 

### Questions

**Comment by rladdusaw** [comment]
Description text provided by Bobray

> While most recent working papers are now freely available online, Princeton has historical collections in paper and microfilm.  Any questions can be directed to bordelon@Princeton.edu
