### ISSUE TITLE
Refactor the PaginatedTable.js component 

### ISSUE THREAD

**Issue by christinach** [pulibrary/static-tables#24]
- [ ] Pass in a configuration for the filtering options
- [ ] Dynamically generate the [filter inputs](https://github.com/pulibrary/marquand-catalogs/blob/c0678b82b0a1f6a99475e7773637ba43ac75b0b9/site/app/components/PaginatedTable.js#L144)
- [ ] Update the [filterRows()](https://github.com/pulibrary/marquand-catalogs/blob/c0678b82b0a1f6a99475e7773637ba43ac75b0b9/site/app/components/PaginatedTable.js#L58) function to use the new dynamic filters.

**Comment by christinach** [comment]
There are hardcoded parts on how the filters work. 
Filter config would help to split into smaller issues.
@maxkadel will split into smaller components and right new tickets for refactoring those components.

**Comment by maxkadel** [comment]
Closed in favor of #58, #59, #61, #62
