### ISSUE TITLE
Create Princeton University Historical Photograph Collection

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/static-tables#40]
### User story
I would like to be able to search and browse the Princeton University Historical Photograph Collection.

### Acceptance criteria

- [x] Page displays the basic Princeton library header
- [x] Page displays the basic Princeton library footer
- [x] Page title is "Princeton University Historical Photograph Collection"
- [x] The base path of the application is available at princeton-university-historical-photograph-collection
- [x] Users can keyword search by Subject
- [ ] ~Users have the option to AND/OR Up to three subjects~ Broken out into #153
- [x] Users can filter by division
- [x] Users can keyword search by Photographer
- [x] Users can filter by image type
- [x] Users can see the collection description below displayed at the top of the page. 
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [x] Update [staging proxy-pass rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf) to point https://library.princeton.edu/special-collections/databases/princeton-university-historical-photograph-collection to https://static-tables-staging.princeton.edu/princeton-university-historical-photograph-collection
- [ ] Update [production proxy-pass rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf) to point https://library.princeton.edu/special-collections/databases/princeton-university-historical-photograph-collection to https://static-tables-staging.princeton.edu/princeton-university-historical-photograph-collection
### Notes
See the [Current URL](https://library.princeton.edu/special-collections/databases/princeton-university-historical-photograph-collection) to review the existing search options available. 
[Current Data File](https://docs.google.com/spreadsheets/d/1HvnfqrbsOFhwQ0Xc0m4mYOj-KkASo83o33yE8BymYss/edit#gid=856275511) - File -> Share -> Publish to web -> dropdown change to CSV - >Publish. Copy the url and use it in the config file for the app.

### Collection Description 
This database contains descriptive information on over 20,000 photographs found within the University Archives Historical Photograph Collection. You may conduct a keyword search to retrieve a listing of photographs that meet your criteria. Information returned will include a general description of the photograph along with pertinent details, such as dates, photographer, and image type, as well as the collection, box, and image number. In addition to this database, finding aids for some divisions (Campus Life, Grounds and Buildings, andStudent Photograph Albums) of the Historical Photograph Collection are available on the web. Furthermore, this database does not include all the photographs extant within the University Archives. Additional information will be added as photos are cataloged.

The Mudd Manuscript Library would like to acknowledge the Friends of the Princeton University Library for their generous support in making this database web-accessible.

### Questions
1. Check with web content team on if we need to include display details about the service unit (i.e. Marquand or Mudd) in these displays or if they can just display the standard Princeton Library Header/Footer like allsearch.

**Comment by sandbergja** [comment]
re-opening to add a subject filter
