### ISSUE TITLE
Create deployment routine using Capistrano

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/static-tables#46]
### What maintenance needs to be done?
We need a way to deploy updates to the application to staging and production machines. In order to be consistent with other projects, we should use Capistrano to deploy. 

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- This application has outgrown the use case for the libstatic infrastructure, and would benefit from being able to deploy independently from the other applications on libstatic.

### Acceptance criteria
 - [ ] You can deploy different branches to staging and production servers using Ansible Tower
 - [ ] You can deploy a specific using `BRANCH=mybranch bundle exec cap [environment] deploy` from your local environment
 - [ ] Build the dist directory. See [allsearch_frontend example](https://github.com/pulibrary/allsearch_frontend/blob/main/config/deploy.rb)

### Implementation notes, if any
- See [PR to add Capistrano to AllSearch Frontend](https://github.com/pulibrary/allsearch_frontend/pull/27) as an example

**Comment by maxkadel** [comment]
This can be worked on prior to the blocking tickets, but cannot be validated before they are completed.

**Comment by rladdusaw** [comment]
If were going to give this app its own box should we stop using the CDN dependencies and use yarn to manage it?

**Comment by rladdusaw** [comment]
The deployment is running successfully but we are seeing an error related to importing modules. I think this is due to us trying to deploy the source, not the dist.
