### ISSUE TITLE
Use the config to apply filters to table

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/static-tables#61]
### What maintenance needs to be done?
Use the FilterConfig to apply the filters to the table based on the values of the data object

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Acceptance criteria
 - [ ] Uses config

### Implementation notes, if any
- Leave as a function on PaginatedTable, but make sure it uses the config

**Comment by christinach** [comment]
closing in favor of working on https://github.com/pulibrary/static-tables/issues/58
