### ISSUE TITLE
Refactor Data object in PaginatedTable.js so it can have different properties

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/static-tables#62]
### What maintenance needs to be done?
Make it so that the data object in PaginatedTable.js can have different properties

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- Need to be able to set different data based on page

### Acceptance criteria
 - [ ] Data object can have different data

### Implementation notes, if any
- Can use a config, or choose a different approach

**Comment by sandbergja** [comment]
I think #81 may have resolved this issue -- it removes date, name, auctionHouse, and city from the `data()` object, if that is the Data object in question.

**Comment by christinach** [comment]
@sandbergja we can close this ticket yes. Thanks for resolving it!

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/static-tables/pull/81
