### ISSUE TITLE
No Code of Conduct

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/static-tables#64]
### Introduction

I would love if all our repositories have a code of conduct. 

### Acceptance criteria

The repo has a code of conduct.

### Notes
See [princeton ansible Code of Conduct](https://github.com/pulibrary/princeton_ansible/blob/main/CODE_OF_CONDUCT.md)

**Comment by christinach** [comment]
Closing in favor of https://github.com/pulibrary/.github/issues/4
