### ISSUE TITLE
Make page title configurable

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/static-tables#70]
### What maintenance needs to be done?
Make page title configurable so we can re-use site for different things

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Acceptance criteria
 - [ ] The text that is currently "Marquand Library of Art and Archaeology" can be replaced with configured text
 - [ ] It maintains the same styling

**Comment by christinach** [comment]
resolves https://github.com/pulibrary/static-tables/pull/76
