### ISSUE TITLE
Make navbar title configurable

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/static-tables#71]
### What maintenance needs to be done?
Make navbar title configurable

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
Needed to make site re-usable

### Acceptance criteria
 - [ ] Can configure text that is currently "Marquand Sales Catalogs"
 - [ ] Maintains styling

**Comment by maxkadel** [comment]
https://github.com/pulibrary/static-tables/pull/76

**Comment by christinach** [comment]
resolves https://github.com/pulibrary/static-tables/pull/76
