### ISSUE TITLE
Use the the history api for routing

### ISSUE THREAD

**Issue by christinach** [pulibrary/static-tables#91]
### Why is this change needed

- Instead of using the event listener to use `#` from `window.location`, use the the history api for routing.
- The nginx configuration cannot accommodate `#` in `try_files` because it interprets it as a fragment.

- We don't want it to conflict with other in page navigation such as 'Skip to content'.

### Notes
See [History api replace method](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState)

**Comment by rladdusaw** [comment]
I don't think we need the history api, it's used for moving through views in a single page application while maintaining the ability to navigate with the back and forward buttons. We just need to get pull then end of the path out of window.location.pathname and supply the appropriate view.

If we ever reach a level of complexity that would require us to manipulate the browser history I think we should adopt the vue-router library.

**Comment by sandbergja** [comment]
Good point, @rladdusaw !  Thanks!  I took that approach in my PR.
